name: deploy

on:
  workflow_call:
    inputs:
      aws_account:
        required: true
        type: string
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm package manager
        uses: pnpm/action-setup@v4
      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/github-actions-role-serverless-mcp
      - name: Deploy project
        run: pnpm cdk deploy serverless-mcp --require-approval never
